#!/usr/bin/env python
import sys
import Gestion



# -*- coding: utf-8 -*-
"""
Created on Sun Mar 28 15:03:33 2021

@author: pierre
"""

for arg in sys.argv:
    print(arg)
    Gestion.init()
    Gestion.parse_file(sys.argv[1])
    Gestion.save_bufer()
    Gestion.persist_db()
    








Gestion.persist_db()

